### ISSUE TITLE
Unable to log into matrix

### ISSUE THREAD

**Issue by KianTheCon** [palepunk/MatrixClient#1]
Running the library with the given example code results in the following serial output. 

```
[00:00:01.152] Connecting to WiFi...
[00:00:01.153] Connected to WiFi
[00:00:01.153] Invalid Matrix ID
[00:00:01.153] Using default server URL: https://matrix.org
[  1195][E][WiFiClientSecure.cpp:144] connect(): start_ssl_client: -1
[00:00:01.202] Connection to matrix.org failed
deserializeJson() failed: [00:00:01.203] EmptyInput
[00:00:01.203] responseBody:
[00:00:01.203] Login failed.
```
Any advice on what I could do to make it work? I should also mention that in order to even get it to try logging in I had to remove everything in the loop function since it would simply error out in PlatformIO (for ESP32).

**Comment by palepunk** [comment]
Looks like the server discovery didn't work, and it tries to connect to matrix.org, which was just an example. To which homeserver did you try to connect, what is the end part of your username (@username:homeserver.tld)?

**Comment by KianTheCon** [comment]
Hi! Thanks for getting back to me. My homeserver is just matrix.org, I created a new acc on element to use as a throwaway for testing this. Here is my whole top part of the code, feel free to attempt using it yourself to see if the issue is something else on my end. 

```
const char* authorizedUserId = "@kiantest:matrix.org";
const char* matrixUser = "kiantest";
const char* matrixPassword = "libpasswordtest";
const char* defaultServerHost = "matrix.org";
```

**Comment by palepunk** [comment]
Hi,
your matrixUser should be "@kiantest:matrix.org". And in an ideal case, your authorized user would be another user. I would register a dedicated user for your esp, and use another one in another client (browser or app) to communicate with the esp

**Comment by KianTheCon** [comment]
I changed it to this and I still get the same serial output error (deserializeJson() failed: [00:00:01.227] EmptyInput)

```
const char* authorizedUserId = "@kster:matrix.org";
const char* matrixUser = "@kiantest:matrix.org";
const char* matrixPassword = "libpasswordtest";
const char* defaultServerHost = "matrix.org"; // if server discovery is not working
```

**Comment by palepunk** [comment]
i forgot to add this line to the example: client.setInsecure();
Please try to add that to the setup part. I've updated the example code

**Comment by KianTheCon** [comment]
Oh ok thanks I did that but it still fails with the following output: (followed by Synced Succesfully repeatedley)

```
[00:00:01.152] Connecting to WiFi...
[00:00:01.153] Connected to WiFi
[00:00:08.330] deserializeJson() failed: 
[00:00:08.331] EmptyInput
[00:00:08.331] responseBody:
[00:00:08.332] Using default server URL: https://matrix.org
deserializeJson() failed: [00:00:15.478] EmptyInput
[00:00:15.479] responseBody:
[00:00:15.479] Login failed.
```

**Comment by palepunk** [comment]
i don't know what's wrong on your side. i've change the code to have configurable log levels and if you set it to debug (like in the example) we may see more.
If you want to use the example as it is, you need to add arduino-libraries/NTPClient to your platformio.ini

**Comment by KianTheCon** [comment]
I've updated my code to the new example code but now it seems im missing some library required for logging (though my code is identical the example and I have all the same libraries). Am I missing something else?

**Comment by KianTheCon** [comment]
Oh wait for some reason I needed to remove and re-add the library to force it to update and now everything is working, sorry about that.

**Comment by palepunk** [comment]
glad to hear
